document.querySelector("#profile-shortcut")?.addEventListener("click",()=>{document.querySelector('[data-page="settings"]')?.click();setTimeout(()=>document.querySelector("#profile-name-input")?.focus(),120)});
const App=window.NomadApp;const expenseCategories=["Housing","Food","Groceries","Transport","Utilities","Health","Education","Shopping","Entertainment","Travel","Insurance","Loan payment","Family support","Subscription","Other expense","Custom"];const incomeCategories=["Salary","Freelance","Business","Bonus","Commission","Investment income","Rental income","Gift","Refund","Interest","Government benefit","Other income","Custom"];let editingAccountId=null;const state=()=>App?.getState();const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
function stats(off=0){const n=new Date(),d=new Date(n.getFullYear(),n.getMonth()+off,1),rows=(state()?.transactions||[]).filter(t=>t.date?.startsWith(monthKey(d)));const income=rows.filter(t=>t.type==="income").reduce((s,t)=>s+App.inMain(t.amount,t.currency),0),expense=rows.filter(t=>t.type==="expense").reduce((s,t)=>s+App.inMain(t.amount,t.currency),0);return{income,expense,balance:income-expense,rows}}
function renderHome(){if(!state())return;const c=stats(),p=stats(-1);document.querySelector("#home-month-expenses").textContent=App.money(c.expense);document.querySelector("#home-month-income").textContent=App.money(c.income);document.querySelector("#home-month-balance").textContent=App.money(c.balance);const ec=document.querySelector("#home-expense-comparison");ec.textContent=!p.expense?(c.expense?"No previous-month comparison":"No spending recorded yet"):`${Math.abs((c.expense-p.expense)/p.expense*100).toFixed(0)}% ${c.expense<=p.expense?"less":"more"} than last month`;const ic=document.querySelector("#home-income-comparison");ic.textContent=!p.income?(c.income?"No previous-month comparison":"No income recorded yet"):`${Math.abs((c.income-p.income)/p.income*100).toFixed(0)}% ${c.income>=p.income?"more":"less"} than last month`;const recent=document.querySelector("#home-recent-transactions"),rows=[...(state().transactions||[])].sort((a,b)=>new Date(b.createdAt||b.date)-new Date(a.createdAt||a.date)).slice(0,5);recent.innerHTML=rows.length?rows.map(t=>`<article class="home-recent-row"><div><strong>${esc(t.category)}</strong><small>${esc(t.note||App.countryName(t.country))} · ${esc(t.date)}</small></div><strong class="${t.type}">${t.type==="income"?"+":"−"}${App.money(t.amount,t.currency)}</strong></article>`).join(""):`<div class="compact-home-empty"><div>◇</div><strong>No transactions yet</strong><span>Add your first expense or income to begin.</span></div>`}
function setCategories(type){
  const sel=document.querySelector("#transaction-account")?.addEventListener("change",syncTransactionAccount);
document.querySelectorAll('.transaction-type-tabs input[name="type"]').forEach(input=>input.addEventListener("change",()=>{if(input.checked)setCategories(input.value)}));
document.querySelector("#transaction-category-select"),opts=type==="income"?incomeCategories:expenseCategories;
  if(sel)sel.innerHTML=opts.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");
  document.querySelector("#custom-category-wrap")?.classList.add("hidden");
  const dialog=document.querySelector("#transaction-dialog"),heading=dialog?.querySelector(".dialog-heading h2"),form=document.querySelector("#transaction-form");
  if(heading)heading.textContent=type==="income"?"Add income":"Add expense";
  if(form?.elements?.type)form.elements.type.value=type;
  const label=document.querySelector("#transaction-account-label");
  if(label)label.childNodes[0].nodeValue=type==="income"?"Which account should receive this income?":"Which account did you pay from?";
}
function syncTransactionAccount(){
  const form=document.querySelector("#transaction-form"),accountId=form?.elements?.accountId?.value;
  const selected=state()?.accounts?.find(a=>a.id===accountId),summary=document.querySelector("#transaction-account-summary");
  if(!selected){summary?.classList.add("hidden");if(form?.elements?.currency)form.elements.currency.value="";if(form?.elements?.country)form.elements.country.value="";return;}
  form.elements.currency.value=selected.currency;
  form.elements.country.value=App.normalizeCountryCode(selected.country);
  document.querySelector("#transaction-selected-account").textContent=`${selected.name} · ${selected.institution||selected.type}`;
  document.querySelector("#transaction-selected-currency").textContent=selected.currency;
  document.querySelector("#transaction-selected-country").textContent=App.countryName(selected.country);
  summary?.classList.remove("hidden");
}
function setTransactionMode(mode){
  const form=document.querySelector("#transaction-form"),tabs=document.querySelector(".transaction-type-tabs");if(!form)return;
  form.dataset.entryMode=mode;
  if(mode==="all"){tabs?.classList.remove("hidden");tabs?.querySelectorAll('input[name="type"]').forEach(x=>x.disabled=false);setCategories(form.elements.type?.value||"expense");}
  else{tabs?.classList.add("hidden");tabs?.querySelectorAll('input[name="type"]').forEach(x=>x.disabled=x.value!==mode);setCategories(mode);}
}
function openEntry(type){const form=document.querySelector("#transaction-form");form?.reset();if(form?.elements?.date)form.elements.date.value=new Date().toISOString().slice(0,10);setTransactionMode(type);syncTransactionAccount();document.querySelector("#transaction-dialog")?.showModal();setTimeout(()=>form?.elements?.accountId?.focus(),50)}
window.NomadTransactionUI={setMode:setTransactionMode,syncAccount:syncTransactionAccount,setCategories};
function balance(a){return Number(a.openingBalance||0)+(state().transactions||[]).filter(t=>t.accountId===a.id).reduce((s,t)=>s+(t.type==="income"?Number(t.amount):-Number(t.amount)),0)}
function renderAccountActions(){document.querySelectorAll("#account-list article[data-id]").forEach(card=>{if(card.querySelector(".account-manage-actions"))return;const id=card.dataset.id;if(!id)return;const x=document.createElement("div");x.className="account-manage-actions";x.innerHTML=`<button type="button" class="secondary account-action" data-edit-account="${id}">Edit account</button><button type="button" class="primary account-action" data-adjust-account="${id}">Adjust balance</button><button type="button" class="account-more-button" data-account-more="${id}" aria-label="More account actions">⋮</button>`;card.appendChild(x)})}
function account(id){return state()?.accounts?.find(a=>a.id===id)}
function openEdit(id){const a=account(id);if(!a)return;editingAccountId=id;const f=document.querySelector("#edit-account-form");f.elements.id.value=id;f.elements.name.value=a.name;f.elements.institution.value=a.institution||"";f.elements.type.value=a.type;App.populateCurrencySelect(f.elements.currency,a.currency);f.elements.currency.value=a.currency;App.populateCountrySelect(f.elements.country,a.country);f.elements.country.value=App.normalizeCountryCode(a.country);document.querySelector("#edit-account-dialog").showModal()}
function openAdjust(id){const a=account(id),f=document.querySelector("#adjust-balance-form");if(!a)return;f.reset();f.elements.account_id.value=id;f.elements.amount.value=balance(a).toFixed(2);document.querySelector("#adjust-balance-dialog").showModal()}
document.addEventListener("click",e=>{const en=e.target.closest("[data-open-entry]");if(en)return openEntry(en.dataset.openEntry);const pg=e.target.closest("[data-page-target]");if(pg)return document.querySelector(`[data-page="${pg.dataset.pageTarget}"]`)?.click();const ed=e.target.closest("[data-edit-account]");if(ed)return openEdit(ed.dataset.editAccount);const ad=e.target.closest("[data-adjust-account]");if(ad)return openAdjust(ad.dataset.adjustAccount)});
document.querySelector("#transaction-category-select")?.addEventListener("change",e=>document.querySelector("#custom-category-wrap")?.classList.toggle("hidden",e.target.value!=="Custom"));document.querySelector("#transaction-form")?.addEventListener("submit",e=>{const f=e.currentTarget;if(f.elements.category?.value==="Custom"&&f.elements.custom_category?.value.trim())f.elements.category.value=f.elements.custom_category.value.trim()},true);
document.querySelector("#edit-account-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=account(f.get("id"));a.name=String(f.get("name")).trim();a.institution=String(f.get("institution")).trim();a.type=f.get("type");a.currency=f.get("currency");a.country=f.get("country");e.currentTarget.closest("dialog").close();App.save("Account updated")});document.querySelector("#delete-account-button")?.addEventListener("click",()=>{if(!editingAccountId||!confirm("Delete this account?"))return;state().accounts=state().accounts.filter(a=>a.id!==editingAccountId);state().transactions.forEach(t=>{if(t.accountId===editingAccountId)t.accountId=null});document.querySelector("#edit-account-dialog").close();App.save("Account deleted")});document.querySelector("#adjust-balance-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=account(f.get("account_id")),type=f.get("adjustment_type"),amt=Number(f.get("amount")),note=String(f.get("note")||"").trim();if(type==="correction")a.openingBalance=Number(a.openingBalance||0)+(amt-balance(a));else state().transactions.push({id:crypto.randomUUID(),type:type==="deposit"?"income":"expense",amount:amt,currency:a.currency,category:type==="deposit"?"Account deposit":"Account withdrawal",country:App.normalizeCountryCode(a.country),accountId:a.id,date:new Date().toISOString().slice(0,10),createdAt:new Date().toISOString(),frequency:"once",note:note||"Balance adjustment"});e.currentTarget.closest("dialog").close();App.save("Balance updated")});document.querySelector("#reset-financial-data")?.addEventListener("click",()=>document.querySelector("#reset-financial-dialog")?.showModal());document.querySelector("#confirm-financial-reset")?.addEventListener("click",()=>{const s=state();App.replaceState({...s,accounts:[],transactions:[],budgets:[],investments:[],goals:[],netWorthSnapshots:[],travel:{country:s.currentCountry||"AL",budget:0,spent:0,days:1}},{persist:true,message:"All financial data has been reset"});document.querySelector("#reset-financial-dialog")?.close()});["nomad:user-ready","nomad:state-saved","nomad:state-replaced","nomad:transactions-rendered"].forEach(n=>window.addEventListener(n,()=>{renderHome();setTimeout(renderAccountActions,100)}));if(App?.getState()){setCategories("expense");renderHome();setTimeout(renderAccountActions,150)}
document.addEventListener("click",event=>{
  const more=event.target.closest("[data-account-more]");
  document.querySelectorAll(".account-popover").forEach(x=>x.remove());
  if(!more)return;
  event.preventDefault();
  event.stopPropagation();
  const id=more.dataset.accountMore;
  const pop=document.createElement("div");
  pop.className="account-popover";
  pop.innerHTML=`<button type="button" data-adjust-account="${id}" data-adjust-mode="correction">Correction</button><button type="button" data-adjust-account="${id}" data-adjust-mode="deposit">Deposit</button><button type="button" data-adjust-account="${id}" data-adjust-mode="withdrawal">Withdrawal</button>`;
  more.closest(".mini-card")?.appendChild(pop);
});
